### PR TITLE
Added filters to file monitor

### PR DESCRIPTION
**Pull request by theWatchmen**
The implementation is pretty simple: filters should be separated by ";" and "*" is used as wildcard. I tried to be careful with memory allocation for the strings, but I might have made some silly mistake. Let me know if that's the case and I will correct it! Also, let me know if you have any further suggestion/comment.

### CODE REVIEW

**Comment by emoon** [comment]
Thanks! The change looks good :)

What I think would be good is to expand the test a bit. So you test both the case with ";" also so a test that perhaps verify "bin;foo" or something similar so that it's covered by the test.

**Comment by theWatchmen** [comment]
I added the test for multiple filter extensions and also improved the match test to be performed only on the file extension (previously it was on the whole path).

**Comment by emoon** [comment]
Very nice!

Thanks for this :)

**Comment by emoon** [comment]
The code doesn't build on Mac and Windows

http://zenic.org:8020/#/builders/1/builds/305/steps/1/logs/stdio
http://zenic.org:8020/#/builders/2/builds/306/steps/1/logs/stdio

**Comment by emoon** [comment]
Using alloca instead of the C99 extension should be fine here imo.

**Comment by emoon** [comment]
Coverity reported this issue also:

Hi,

Please find the latest report on new defect(s) introduced to emoon/ProDBG found with Coverity Scan.

1 new defect(s) introduced to emoon/ProDBG found with Coverity Scan.


New defect(s) Reported-by: Coverity Scan
Showing 1 of 1 defect(s)


** CID 94122:  Security best practices violations  (STRING_OVERFLOW)
/src/prodbg/core/file_monitor.cpp: 89 in updateCallbacks(event_t *)()


________________________________________________________________________________________________________
*** CID 94122:  Security best practices violations  (STRING_OVERFLOW)
/src/prodbg/core/file_monitor.cpp: 89 in updateCallbacks(event_t *)()
83     		    // NOTE(marco): we could probably lower the string length
84     		    char filter_extensions[filter_count][256];
85     		    found = strtok(file_filters, delimiter);
86     		    int current_filter = 0;
87     		    while (found != NULL)
88     		    {		    
   CID 94122:  Security best practices violations  (STRING_OVERFLOW)
   You might overrun the 256 byte fixed-size string "filter_extensions[current_filter++]" by copying "found" without checking the length.
89     			strcpy(filter_extensions[current_filter++], found);
90     			found = strtok(NULL, delimiter);
91     		    }		
92     
93     		    bool matching_filter = false;		
94     		    for (int filter_index = 0; filter_index < filter_count; ++filter_index)

**Pull request merged**
