### PR TITLE
Moved bgfx & bx to git submodules

### LINKED ISSUE #199: Move bgfx to git submodule
As we have the source unmodified now (I think) it should be possible to use it as a submodule instead.

### PR DESCRIPTION
**Pull request by v3n**
Hi guys,

This should resolve #199, I've been following the project for awhile and saw something I could jump in on and contribute to. Thanks for all your hard work!

Cheers!

### CODE REVIEW

**Comment by emoon** [comment]
Thanks! Will wait for the CI to pass and the accept this :)

**Comment by emoon** [comment]
@v3n Hey there is some compile error here https://ci.appveyor.com/project/emoon/prodbg/build/435 do you think that can be fixed before I accept this?

**Comment by v3n** [comment]
Yep, looking at it now, looks like an upgraded warning. I'll probably submit an upstream fix.

**Comment by emoon** [comment]
You can just do the fix and push to your master and it will appear here.

**Comment by v3n** [comment]
I submitted the upstream fix to bgfx, when it's merged I'll move the submodule remote back to that repository and upload the final commit for this PR.

**Comment by emoon** [comment]
Alight. Thanks!

**Comment by emoon** [comment]
Seems Mac build is  broken :(

```objc
/Users/danielcollin/code/prodbg/src/native/external/bgfx/src/renderer_mtl.mm:437:58: error: cannot initialize a parameter of type 'MTLFeatureSet' with an rvalue of type 'int'
                                        g_caps.maxTextureSize = m_device.supportsFeatureSet(4 /* iOS_GPUFamily3_v1 */) ? 16384 : 8192;
                                                                                            ^
/Users/danielcollin/code/prodbg/src/native/external/bgfx/src/renderer_mtl.h:133:41: note: passing argument to parameter '_featureSet' here
                bool supportsFeatureSet(MTLFeatureSet _featureSet)
                                                      ^
/Users/danielcollin/code/prodbg/src/native/external/bgfx/src/renderer_mtl.mm:443:82: error: cannot initialize a parameter of type 'MTLFeatureSet' with an rvalue of type 'int'
                                g_caps.maxFBAttachments = uint8_t(bx::uint32_min(m_device.supportsFeatureSet(1 /* MTLFeatureSet_iOS_GPUFamily2_v1 */) ? 8 : 4, BGFX_CONFIG_MAX_FRAME_BUFFER_ATTACHMENTS));
                                                                                                             ^
/Users/danielcollin/code/prodbg/src/native/external/bgfx/src/renderer_mtl.h:133:41: note: passing argument to parameter '_featureSet' here
                bool supportsFeatureSet(MTLFeatureSet _featureSet)
                                                      ^
/Users/danielcollin/code/prodbg/src/native/external/bgfx/src/renderer_mtl.mm:521:49: error: assigning to 'MTLPixelFormat' from incompatible type 'unsigned long'
                                s_textureFormat[TextureFormat::D24S8].m_fmt = m_device.depth24Stencil8PixelFormatSupported() ?
```

**Comment by v3n** [comment]
How in the world does it pass locally for me as well as in CI?!

That's super weird, I'll investigate tonight.

**Comment by emoon** [comment]
CI doesn't have Mac build (but I just added that)

**Comment by emoon** [comment]
I have the issue on both my Macs (I have El Caption and XCode 7.3.1)

**Comment by emoon** [comment]
@v3n as as bgfx is now updated with your fixes do you think you can do another PR with the code from the main repo?

**Pull request merged**
